<?php

/**
 * @file
 * Provides CAS authentication for Drupal.
 */

use Drupal\user\RoleInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_cron().
 *
 * Delete stale, unused PGTs.
 */
function cas_cron() {
  // PGTs older than one hour get discarded.
  db_delete('cas_pgt_storage')
    ->condition('timestamp', time() - 3600, '<=')
    ->execute();
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function cas_user_role_delete(RoleInterface $role) {
  $config = \Drupal::configFactory()->getEditable('cas.settings');
  $auto_assigned_roles = $config->get('user_accounts.auto_assigned_roles');
  $array_key = array_search($role->id(), $auto_assigned_roles, TRUE);
  if ($array_key) {
    // Remove the role from the auto-assigned roles.
    unset($auto_assigned_roles[$array_key]);
    $config->set('user_accounts.auto_assigned_roles', $auto_assigned_roles)->save();
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cas_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  _cas_alter_user_form($form);

  // Set default value of the CAS username if this user already has one set.
  $cas_user_manager = \Drupal::service('cas.user_manager');
  $account = $form_state->getFormObject()->getEntity();
  $cas_username = $cas_user_manager->getCasUsernameForAccount($account);
  if ($cas_username) {
    $form['cas_username']['#default_value'] = $cas_username;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cas_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  _cas_alter_user_form($form);
}

/**
 * Alter the user entity form to include a textfield for CAS username.
 *
 * @param array $form
 *   The user entity form.
 */
function _cas_alter_user_form(&$form) {
  $form['cas_username'] = [
    '#type' => 'textfield',
    '#title' => t('CAS Username'),
    '#description' => t('The CAS username to associate with this user. Typically the same as the Drupal username. This must be entered to allow this user to authenticate with CAS.'),
    '#access' => \Drupal::currentUser()->hasPermission('administer users'),
    '#maxlength' => 128,
  ];

  // We cannot apply form validation method directly to buttons on entity forms
  // anymore so apply it to the whole form instead.
  $form['#validate'][] = '_cas_user_form_validate';
  $form['actions']['submit']['#submit'][] = '_cas_user_form_submit';
}

/**
 * Validation callback for the user entity form.
 *
 * Verify that the provided CAS username is not already taken by someone else.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 */
function _cas_user_form_validate(&$form, FormStateInterface $form_state) {
  // Verify that it was the save / register button that was clicked. We don't
  // want to run our validation if this was for a 'cancel account' action.
  if (in_array('::save', $form_state->getTriggeringElement()['#submit'])) {
    // The externalauth module does not provide this validation so we have to
    // implement it ourselves. See https://drupal.org/node/2804797.
    $cas_username = $form_state->getValue('cas_username');
    if (!empty($cas_username)) {
      $cas_user_manager = \Drupal::service('cas.user_manager');
      $existing_uid = $cas_user_manager->getUidForCasUsername($cas_username);
      $user_being_edited = $form_state->getFormObject()->getEntity();

      if ($existing_uid && $existing_uid !== $user_being_edited->id()) {
        $form_state->setError($form['cas_username'], t('The specified CAS username is already in use by another user.'));
      }
    }
  }
}

/**
 * Submit callback for the user entity form.
 *
 * Save (or remove) the association of the CAS username to this edited user.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 */
function _cas_user_form_submit($form, FormStateInterface $form_state) {
  $cas_user_manager = \Drupal::service('cas.user_manager');
  $account = $form_state->getFormObject()->getEntity();
  if ($form_state->getValue('cas_username')) {
    $cas_user_manager->setCasUsernameForAccount($account, $form_state->getValue('cas_username'));
  }
  else {
    $cas_user_manager->removeCasUsernameForAccount($account);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a link to login via CAS on the user login form.
 */
function cas_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $config = Drupal::config('cas.settings');

  // Cached form must be busted if we alter CAS settings.
  $form['#cache']['tags'] = array_merge($form['#cache']['tags'], $config->getCacheTags());

  $enabled = $config->get('login_link_enabled');
  if ($enabled) {
    $url = new Url('cas.login', array(), array(
      'attributes' => array(
        'class' => array('cas-login-link'),
      ),
    ));

    $form['cas_login_link'] = [
      '#type' => 'link',
      '#url' => $url,
      '#title' => $config->get('login_link_label'),
      '#weight' => -1,
    ];
  }
}

/**
 * Implements hook_help().
 */
function cas_help($route_name, \Drupal\Core\routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.cas':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = array('settings' => $settings);
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
}
