<?php

/**
 * @file
 * Provides CAS authentication for Drupal.
 */

const CAS_NO_LINK = 0;
const CAS_ADD_LINK = 1;
const CAS_MAKE_DEFAULT = 2;
const CAS_CHECK_NEVER = -2;
const CAS_CHECK_ONCE = -1;
const CAS_CHECK_ALWAYS = 0;
const CAS_REQUIRE_SPECIFIC = 0;
const CAS_REQUIRE_ALL_EXCEPT = 1;

/**
 * Implements hook_cron().
 *
 * Delete stale, unused PGTs.
 */
function cas_cron() {
  // PGTs older than one hour get discarded.
  db_delete('cas_pgt_storage')
    ->condition('timestamp', time() - 3600, '<=')
    ->execute();
}
